# Generated by Django 4.2.11 on 2026-03-02 14:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Boss/Admin (總管理)'), ('mami', 'Mami (店長)'), ('agent', 'Agent (經紀人)'), ('staff', 'Staff (員工)')], default='staff', max_length=10, verbose_name='角色')),
                ('employee_code', models.CharField(blank=True, help_text='每店唯一，例如 YIBA', max_length=20, verbose_name='員工編號')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶列表',
                'permissions': [('view_all_users', 'Can view all users across shops'), ('manage_shop_users', 'Can manage users within own shop'), ('manage_agent_employees', 'Can manage own agent employees')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(verbose_name='上班時間')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='下班時間')),
                ('work_segment', models.IntegerField(choices=[(1, '第一班'), (2, '第二班')], default=1, verbose_name='班次')),
                ('note', models.TextField(blank=True, verbose_name='補簽說明')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='attendance_proofs/%Y/%m/', verbose_name='補簽憑證')),
                ('status', models.CharField(choices=[('normal', '正常'), ('pending_correction', '待審核補簽'), ('approved', '已核准'), ('rejected', '已拒絕')], default='normal', max_length=20, verbose_name='狀態')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
            ],
            options={
                'verbose_name': '出勤記錄',
                'verbose_name_plural': '出勤記錄列表',
                'ordering': ['-clock_in'],
                'permissions': [('approve_attendance_correction', 'Can approve attendance correction'), ('view_all_attendance', 'Can view attendance for all employees')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '總公司',
                'verbose_name_plural': '總公司列表',
                'permissions': [('manage_company', 'Can manage company settings'), ('view_all_companies', 'Can view all companies (platform admin)')],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('is_24h', models.BooleanField(default=False, verbose_name='24小時營業')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='core.company', verbose_name='所屬總公司')),
            ],
            options={
                'verbose_name': '分店',
                'verbose_name_plural': '分店列表',
                'permissions': [('manage_shop', 'Can manage shop settings')],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='桌號/名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.shop', verbose_name='所屬分店')),
            ],
            options={
                'verbose_name': '桌次',
                'verbose_name_plural': '桌次列表',
                'permissions': [('manage_tables', 'Can manage tables within shop')],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模式名稱')),
                ('period_type', models.CharField(choices=[('weekly', '週期'), ('monthly', '月期')], default='monthly', max_length=10, verbose_name='週期類型')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='總時數')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_modes', to='core.shop', verbose_name='所屬分店')),
                ('users', models.ManyToManyField(blank=True, related_name='work_modes', to=settings.AUTH_USER_MODEL, verbose_name='適用員工')),
            ],
            options={
                'verbose_name': '上班模式',
                'verbose_name_plural': '上班模式列表',
                'permissions': [('manage_work_modes', 'Can manage work modes')],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='core.attendance', verbose_name='出勤記錄')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.table', verbose_name='桌次')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
            ],
            options={
                'verbose_name': '桌次服務記錄',
                'verbose_name_plural': '桌次服務記錄列表',
                'ordering': ['-start_time'],
                'permissions': [('assign_table', 'Can assign employees to tables')],
            },
        ),
        migrations.CreateModel(
            name='SalaryDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salary_add', '薪資加項'), ('salary_deduct', '薪資扣項'), ('damage', '損壞賠償')], max_length=20, verbose_name='類型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額 (TWD)')),
                ('description', models.TextField(verbose_name='說明')),
                ('date', models.DateField(verbose_name='日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_damages', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
            ],
            options={
                'verbose_name': '薪資調整/損壞記錄',
                'verbose_name_plural': '薪資調整/損壞記錄列表',
                'ordering': ['-date'],
                'permissions': [('manage_salary_damage', 'Can add/edit salary damage records')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='BOSS 層級直接綁定總公司；其他角色透過分店間接屬於總公司', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company', verbose_name='所屬總公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Mami / Agent / Staff 必填；BOSS 可為空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.shop', verbose_name='所屬分店'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__gt', '')), fields=('shop', 'employee_code'), name='unique_employee_code_per_shop'),
        ),
    ]
